import java.util.*;
public class Main3{
    public static void main(String [] args){
        Triangle();
    }
    public static void leap(){ Scanner sc = new Scanner(System.in); System.out.println("Enter the month (digit)"); int month = sc.nextInt(); System.out.println("enter the year (4 digit)"); boolean leapYear = leapChck(sc.nextInt()); switch(month){ case 1: System.out.println("January, 31 days"); break; case 2: if(leapYear){ System.out.println("February, LEAP YEAR. 29 days"); } else System.out.println("Febuary, 28 days"); break; case 3: System.out.println("March, 31 days"); break; case 4: System.out.println("April, 30 days"); break; case 5: System.out.println("May, 31 days"); break; case 6: System.out.println("June, 30 days"); break; case 7: System.out.println("July, 31 days"); break; case 8: System.out.println("August, 31 days"); break; case 9: System.out.println("September, 30 days"); break; case 10: System.out.println("October, 31 days"); break; case 11: System.out.println("November, 30 days"); break; case 12: System.out.println("December, 31 days"); break; default: System.out.println("Invalid month"); } } public static boolean leapChck(int age){if(age%4==0&&age%100!=0){ return true; } else if(age%400==0){ return true; } return false; }
    public static void Calc(){ Scanner sc = new Scanner(System.in); System.out.println("Enter a Positive integer"); int N = sc.nextInt(); int totalAdd = 0; int totalDiv = 0; for(int i = 1;i<=N;i++){ totalAdd+=i; if(i%3==0){ totalDiv+=i; } } System.out.println("Total sum all numbers from 1 to "+N+" is "+totalAdd+", And the total of all numbers divisible by 3 from 1 to "+N+" equals "+totalDiv); }
    public static void PIN(){ Scanner sc = new Scanner(System.in); System.out.println("What is your 4 digit pin?"); short Pin = sc.nextShort(); if(Pin>10000||Pin<0) { short input = 0; for (int i = 3; i != 0 && input != Pin; i--) { System.out.println("Enter your pin. You have " + i + " attempts remaining."); input = sc.nextShort(); } if (input == Pin) { System.out.println("Access granted."); } else { System.out.println("Reached maximum attempts. Access denied."); } } else{ System.out.println("PIN NOT WITHIN RANGE"); } }
    public static void Bank(){ float balance = 1000.00F; boolean cont = true; byte selection; Scanner sc = new Scanner(System.in); float input;String chck = ""; do{ System.out.println("Select a option.\n1-Check Balance\n2-Deposit\n3-Withdraw\n4-Exit"); chck = sc.nextLine(); try { Byte.parseByte(chck); selection=Byte.parseByte(chck); switch(selection){ case 1: System.out.println("Balance: $"+balance); break; case 2: System.out.println("How much would you like to deposit?"); balance+=sc.nextFloat(); break; case 3: System.out.println("How much would you like to withdraw?"); input=sc.nextFloat(); if(input<+500&&input<=balance&&input>0){ balance-=input; input=0; } else{ System.out.println("Invalid input. Please try again."); } break; case 4: cont = false; break; default: System.out.println("Invalid input. Please try again."); break; } } catch (NumberFormatException nfe) { System.out.println("Invalid input. Please try again."); } }while(cont); sc.close(); }
    public static void Triangle(){ Scanner sc = new Scanner(System.in); System.out.println("Enter the Height of the triangle");int dimention = sc.nextInt();char cur = '*'; char[][] triangle = new char[dimention][]; for(int i=dimention-1;i>=0;i--){ triangle[i] = new char[i+1]; for(int j=0;j<i+1;j++){ if(cur=='*'){ triangle[i][j]='*'; cur='#'; }else{ triangle[i][j]=cur; cur='*'; } System.out.print(triangle[i][j]+", "); } System.out.println(); } }
    public static void average(){

    }
}